#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Nonsense wrapper for handling breakage in `ipmitool` when there's anything out of the ordinary.
#
# This is intended to be called by `forge-scout` and if `lan print` are the
# arguments, then it will instead run `bmc-config` from the freeipmi tools
# disribution included in Debian as well.
#
# Written by MICHAEL BASNIGHT EVEN THOUGH MY NAME IS ON THE GIT BLAME I DID NOT DO THIS.
#
set -o pipefail

if [ "$1" == "lan" ] && [ "$2" == "print" ]; then
        exec bmc-config --checkout -S Lan_Conf | awk '/\tIP_Address / {print "IP Address              : " $2}; /\tMAC_Address / {print "MAC Address             : " $2}'
else
        exec /usr/bin/ipmitool $@
fi
