## Global settings
global:
  namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: site-controller

## Image for the password unexpirer (must be set by user)
image:
  repository: ""
  tag: ""

env:
  EGX_ADMIN_PASSWORD: ""
  EGX_RCPROXY_PASSWORD: ""

annotations:
  configmap.reloader.stakater.com/reload: "nvpasswd-unexpirer-script"

# Config files - can be overridden
configFiles:
  script: "" # If empty, uses the default from files/
